version: "3.8"
services:
  postgres-inventory:
    image: postgres:16-alpine
    container_name: squad2-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      POSTGRES_DB: inventory_db
    volumes:
      # 1. Volume de Persistência
      - postgres_inventory_data:/var/lib/postgresql/data
      # 2. Volume de Inicialização
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
volumes:
  postgres_inventory_data:
networks:
  ecommerce-network:
    external: true
